### ISSUE TITLE
Identify/create communication mechanism  and add to CONTRIBUTING.md

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#1]

**Comment by shahrokhDaijavad** [comment]
I had a call with JJ Asghar of the IBM open source office and he explained to me the problem with setting up a “synchronous” external communication channel like slack. The amount of 24/7 moderation to keep up with this is prohibitive. I am convinced that we should NOT set up an external slack channel at this time and stay with the usual asynchronous communication channel of raising issues in the repo and reaching out to the moderators (if needed). We can of course have an internal slack channel, which I will set up.
