### ISSUE TITLE
[Bug] "Simplest Transform Tutorial" hard-codes IBM Cloud information

### ISSUE THREAD

**Issue by deanwampler** [data-prep-kit/data-prep-kit#107]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Documentation

### What happened + What you expected to happen

[Running the "simplest" tutorial](https://github.com/IBM/data-prep-kit/blob/dev/data-processing-lib/doc/simplest-transform-tutorial.md#running) assumes IBM Cloud:

```
python noop_main.py --noop_sleep_msec 2 \
  --run_locally True  \
  --s3_cred "{'access_key': 'KEY', 'secret_key': 'SECRET', 'cos_url': 'https://s3.us-east.cloud-object-storage.appdomain.cloud'}" \
  --s3_config "{'input_folder': 'cos-optimal-llm-pile/test/david/input/', 'output_folder': 'cos-optimal-llm-pile/test/david/output/'}"
```

Can you provide some dummy test data in the repo and use that instead? What would be the command-line flags for local storage?

It's fine with me to leave in an S3 (_true_ S3) example for those users so equipped, but otherwise, this is hardly a "local" example and I'm currently blocked.

I would try submitting a PR, but I'm not sure what the changed CLI flags would be for local use.

### Reproduction script

N/A

### OS

MacOS (limited support)

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
I pushed PR #110 that I believe fixes this and a lot of the other docs to match recent refactorings.

**Comment by Bytes-Explorer** [comment]
Can this be closed ?

**Comment by daw3rd** [comment]
@deanwampler can you please verify the fix?  Thanks.

**Comment by deanwampler** [comment]
Confirmed. Thanks.

**Comment by deanwampler** [comment]
Closing as fixed...
