### ISSUE TITLE
[Feature] Clarity in Readme file for noop transform

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#123]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/universal/noop

### Feature

Clarity requested by Dean in:  data-prep-kit/transforms/universal/noop/README.md

Can you provide more explanation about what the configuration values, do, e.g.,
• noop_sleep_sec : specifies the number of seconds to sleep during table transformation. What does "during" mean. Is it really before or after processing starts? Is this something "real" transformers might want, e.g., to allow something to happen in the background before reading starts?
• noop_pwd - specifies a dummy password not included in metadata. I assume this is for accessing the file. Is a user name also required?
     
Of course, you said these are examples, but I would go to extra effort to clarify specific behaviors, to encourage users to do the same.
As a general note about configuration parameter names, would it be better to use a hierarchy, like noop.sleep.sec so that in the noop context, you would just look at sleep.sec in the config file. I made sleep a parent in case you added more options, e.g.,
    noop.sleep.enable = false
    noop.sleep.sec = 2

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
I have since added/merged some more details on this parameters.   I'll mark this fixed for now, but @deanwampler can verify.
