### ISSUE TITLE
[Feature] Change the Kind cluster ingress configuration

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#130]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

The current ingress configuration is that MinIO takes the default root URL path. Kfp requests should start from `kfp/`. The finishing slash is important; without it, Nginx forwards user requests to MinIO, which leads to user confusion. 
From a user perspective, the KFP entry point is not just important, it's the main entry point. This emphasis guides users and enhances the overall usage of the system. 

Note: the nginx has the Ray API Server ingress as well.
Note: the changes requires updates in teh installation scripts and in the documentation.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
The current ingress configuration is that MinIO takes the default root URL path. That is the only option to make `mc` work correctly. Changing Minio URL path to anything else is going to break mc usage, see https://min.io/docs/minio/linux/reference/minio-mc/mc-alias.html

**Comment by blublinsky** [comment]
@roytman I think it what it is for now

**Comment by roytman** [comment]
we can run 2 separate ingress controllers: one for KFP as a main user entry point and another one for testing/debugging with MinIO and Ray 
it will prevent user confusions

**Comment by roytman** [comment]
it is done
