### ISSUE TITLE
[Feature] Add support to ingest PDF files

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#162]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Tools/ingest2parquet

### Feature

We would like to add ability to read PDF files and convert them to parquet files, which can go through other processing modules like dedup, filtering etc. Today we have support for .zip files via [ingest2parquet](https://github.com/IBM/data-prep-kit/tree/dev/tools/ingest2parquet) module

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
@Bytes-Explorer Should we work with Peter Staar on getting his module for pdf processing?
