### ISSUE TITLE
Clarification in the simple_transform_pipeline.md file 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#163]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

I think many first-time users of kfp will start from the **simple_transform_pipeline.md** file, not having read the kind readme file, in which manual installation of software like helm and kind is mentioned. So, when they get to the **preparing kind cluster** in this file, they think **make setup** would install pre-req software too. I suggest adding a link in the **simple_transform_pipeline.md** file that would take the user to the kind readme file, like this: 

Assuming you have pre-installed the software components specified **here**  (the link to the kind readme file), you can create a Kind cluster with all required software installed using the following command: **make setup**

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
@roytman  If you agree with this, I will make the change and submit a PR.

**Comment by roytman** [comment]
@shahrokhDaijavad I want to reorganize the KFP documentation, and I can include the issue fix in it. I just did not have time. If you want to change it separately, I'm OK with it, but maybe please wait for a day or two.

**Comment by shahrokhDaijavad** [comment]
OK, @roytman . Thanks. I won't change and wait until you reorganize the KFP documentation.
