### ISSUE TITLE
[Feature] Implement a super-pipeline for Code processing 

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#173]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Implement a super pipeline that will combine all code-processing steps.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by roytman** [comment]
@himapatel1 , please provide the Code processing order and maybe the input data.

**Comment by Bytes-Explorer** [comment]
Lets follow what we have here https://github.com/IBM/data-prep-kit/tree/dev/examples for order. All the existing test datasets we have can be used. Let me know if you need me to point you to them.

**Comment by revit13** [comment]
> Lets follow what we have here https://github.com/IBM/data-prep-kit/tree/dev/examples for order. All the existing test datasets we have can be used. Let me know if you need me to point you to them.

@Bytes-Explorer I do not see malware there...  where it should be placed? Thanks

**Comment by Bytes-Explorer** [comment]
@revit13 It can be placed right after code quality.

**Comment by Bytes-Explorer** [comment]
@revit13 @roytman It would be nice if a user can change the order as per their wish. They can provide input in a JSON. Is that kind of automation possible? If this is more work, we can create a new issue for it and you can also leverage Arun/Sai's help.

**Comment by roytman** [comment]
> @revit13 @roytman It would be nice if a user can change the order as per their wish. They can provide input in a JSON. Is that kind of automation possible? If this is more work, we can create a new issue for it and you can also leverage Arun/Sai's help.

@Bytes-Explorer , I work with Arun and Sai. The automation pipeline generation is in next steps. In the current version, user is able to skip steps that he would like to.

**Comment by Bytes-Explorer** [comment]
Thanks Alexey, lets make a new issue for the automation pipeline generation, so that we dont miss it.

**Comment by roytman** [comment]
See https://github.com/IBM/data-prep-kit/issues/182
