### ISSUE TITLE
[Feature] support KFPv2 

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#174]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

We have to support KFPv2; it is a prerequisite for executing our workflows on modern systems, such as the latest ODH and OpenShift AI. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
Sorry, @roytman As I was experimenting with GitHub projects, this got closed inadvertently and I reopened it.

**Comment by roytman** [comment]
No problem.

**Comment by roytman** [comment]
I am closing it.

- We updated the shared libraries to work with KFPv1 and KFPv2
- All pipelines were updated
- Documentation and the build process were updated
- KFPv2 automatic tests were added.

We have to implement a KDPv2 supper pipeline, which will be done separately issue.
