### ISSUE TITLE
Failed to run/setup noop transformer on windows.

### ISSUE THREAD

**Issue by ykalathiya** [data-prep-kit/data-prep-kit#192]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/universal/noop

### What happened + What you expected to happen

I'm trying to setup/run noop transformer on my windows machine. When I make setup/build it failed with error:
```make build
process_begin: CreateProcess(NULL, # Help: Recursively build in all subdirs, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:39: build] Error 2```

### Reproduction script

On windows machine
1. clone the repo
2. cd D:\code\license_remove\license_filter\data-prep-kit\data-processing-lib
3. make build/setup

### Anything else

_No response_

### OS

Windows WSL

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by revit13** [comment]
Hi @ykalathiya are you running on windows or windows wsl (ubuntu)? Thanks

**Comment by ykalathiya** [comment]
I'm running on windows.

**Comment by shivdeep-singh-ibm** [comment]
The makefiles in the current build are not portable to windows. Please try to use wsl on windows to run.

**Comment by ykalathiya** [comment]
Okk thanks for help.
