### ISSUE TITLE
Define Inner-Outer repo sync process

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#204]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

Define a process on how to sync inner and outer repos holistically

This process needs to be planned carefully, since some features of inner repo like support for Lakehouse are not needed in the outer repo

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
This is a duplicate issue and being tracked and worked on in a different repo.
