### ISSUE TITLE
KFP pipeline for doc quality module

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#211]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Of course, this will be done after the move for this module from the inner to outer repo has been completed. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Mohammad-nassar10** [comment]
Where can we find the implementation code of the transform? Is it still not merged yet?

**Comment by shahrokhDaijavad** [comment]
Right, @Mohammad-nassar10.  It is not merged yet. It is in the inner repo, but after the current immediate priorities, it will be copied to the open source repo.

**Comment by roytman** [comment]
If we are talking about [this](https://github.com/IBM/data-prep-kit/tree/dev/transforms/code/code_quality) transformer, it is implemented and tested on KFPv1 and OpenShift AI (KFPv2).

**Comment by shahrokhDaijavad** [comment]
No, @roytman. We are talking about the **doc quality** transform and not the **code quality** transform. The former has not been merged yet and there is a PR against it. (https://github.com/IBM/data-prep-kit/pull/282)) It is going through some changes right now and once it is merged (not in this release), creating a pipeline for it becomes a priority.
