### ISSUE TITLE
KFP pipeline for the lang id module 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#212]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Of course, this will be done after the move for this module from the inner to outer repo has been completed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Mohammad-nassar10** [comment]
Where can we find the implementation code of the transform? Is it still not merged yet?

**Comment by shahrokhDaijavad** [comment]
Right, @Mohammad-nassar10.  It is not merged yet. It is in the inner repo, but after the current immediate priorities, it will be copied to the open source repo.

**Comment by shahrokhDaijavad** [comment]
@Mohammad-nassar10 and @roytman This module has now been merged and tested, so KFP pipeline for it is now in order.

**Comment by roytman** [comment]
hi @shahrokhDaijavad , the pipelines were implemented in the same PR, so you can close the issue.

**Comment by shahrokhDaijavad** [comment]
Great. Thanks, @roytman and @Mohammad-nassar10 .
