### ISSUE TITLE
Support transform specific TransformStatistics aggregator 

### ISSUE THREAD

**Issue by sapthasurendran** [data-prep-kit/data-prep-kit#234]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

Need support to return a dictionary metadata from transform function. Also need a mechanism to overwrite  TransformStatistics function to help iterate over the dictionary metadata and write the aggregated results back to s3. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
@daw3rd We want to prioritise this. Lets chat when you are back from vacation.

**Comment by blublinsky** [comment]
What exactly is the end goal here? What are we trying to do?

**Comment by shivdeep-singh-ibm** [comment]
Current TransformStatistics are numbers and don't support custom aggregation.

However it is possible to extend TransformRuntime to run addtional actors to collect this info.

**Comment by shivdeep-singh-ibm** [comment]
Closing this issue since we would extend TransformRuntime for the transform.
