### ISSUE TITLE
Add a README file to the new Ingest2parquet transform 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#238]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

A README file is needed in this directory: transforms/code/ingest_2_parquet/ray (as consistent with all other transforms)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
@shahrokhDaijavad, I do not think it is for me. It probably should go to Sapta

**Comment by shahrokhDaijavad** [comment]
Fair enough, @blublinsky. Let me assign @sapthasurendran, since it could be some simple editing of the Readme file that is already in the tools directory for this, i.e., tools/ingest2parquet/README.md

**Comment by blublinsky** [comment]
@shahrokhDaijavad can you also ask her to remove the tools directory once she is happy with the current implementation

**Comment by shahrokhDaijavad** [comment]
Yes, @blublinsky I agree that we should not have 2 modules doing the same thing. @Bytes-Explorer and @sapthasurendran, If after a review of the new ingest2parquet by Saptha, she is happy with it, the old code in the tools directory should be removed.

**Comment by sapthasurendran** [comment]
@blublinsky could you please point me to the new ingest2parquet ?

**Comment by blublinsky** [comment]
https://github.com/IBM/data-prep-kit/tree/dev/transforms/code/ingest_2_parquet

**Comment by sapthasurendran** [comment]
@blublinsky Looking at the project structure and the readme  [here](https://github.com/IBM/data-prep-kit/blob/dev/transforms/universal/noop/README.md) , python and ray transforms are in different directories. In the latest [ingest_2_parquet](https://github.com/IBM/data-prep-kit/tree/dev/transforms/code/ingest_2_parquet)  these files are placed inside a single folder. For consistency can we have separate folders for different runtime?

**Comment by blublinsky** [comment]
thank you @sapthasurendran, one of the questions for you is whether we should remove tools directory completely?
Also feel free to do any code refactoring

**Comment by Bytes-Explorer** [comment]
We need to retain the tools directory for other things that are not transforms and other modules that will be added soon. I still propose to keep this under Tools, though I don't have a very strong opinion on it, so can go with what the group suggests.

**Comment by blublinsky** [comment]
To be more specific, I am asking whether we keep both versions of the code. Regardless of the directory

**Comment by Bytes-Explorer** [comment]
Ah I see. No Boris, we should keep only one, the latest one. My requests would be to make sure that the functionality is the same as proven via testing and @shivdeep-singh-ibm should be able to update his example notebook before removing the older one. Many people are using the notebook, so will be good if that experience is not broken. 

@blublinsky do you want to please help with the example files we have, then this can proceed further?
cc @shahrokhDaijavad

**Comment by blublinsky** [comment]
Thank you @Bytes-Explorer , this is out of my hands now. Its up to @sapthasurendran and @shivdeep-singh-ibm to proceed further

**Comment by daw3rd** [comment]
I have done some cleanup in code2parquet and now PR #329 supersedes #324.  @shivdeep-singh-ibm @sapthasurendran looking for your review on #329.
