### ISSUE TITLE
[Logging Bug] Missing final count of processed files

### ISSUE THREAD

**Issue by dhirajjoshi16** [data-prep-kit/data-prep-kit#242]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### What happened + What you expected to happen

There's a mismatch between _displayed number of files processed_ (at the end of a KFP run) vs `total number of files actually processed`. It could be something do to with log flush. e.g., see below

```
....INFO - Number of files is 628, source profile ....
.....
.....
.....
....INFO - Completed 373 files in 3.742639700571696 min....
....INFO - Completed processing in 8.562959388891857 min...
....INFO - done flushing in 0.08876967430114746 sec....
```

### Reproduction script

This is consistently happening for all KFP runs.

### OS

Red Hat Enterprise Linux (RHEL)

### Python

3.10.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by roytman** [comment]
These messages are generated by `data-processing-lib` the issue's component should be `Library/Core`

**Comment by dhirajjoshi16** [comment]
Thanks @roytman

**Comment by shahrokhDaijavad** [comment]
Hi, @dhirajjoshi16 .  @blublinsky has fixed this bug and after his PR#272 gets merged, can you please verify the fix? Thanks.

**Comment by dhirajjoshi16** [comment]
Sounds good @shahrokhDaijavad. Thanks a lot @blublinsky

**Comment by shahrokhDaijavad** [comment]
@dhirajjoshi16 The fix by @blublinsky is only in the open source repo and I believe the tests you guys are doing are with the inner repo code, so until we find a good way of syncing between the inner and outer repos, I don't think you can verify the fix.

**Comment by dhirajjoshi16** [comment]
Yes we will wait for the sync. @yuanchi2807

**Comment by blublinsky** [comment]
Fixed

**Comment by dhirajjoshi16** [comment]
Thanks a lot @blublinsky
