### ISSUE TITLE
[Feature] KFP timeouts 

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#249]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

KFPv1 allows to set a timeout to each component and a timeout to the entire pipeline. However, with KFPv2 we can set timeouts to components only, and we cannot set a timeout to the entire pipeline. 

We have to check what will be the behavior of pipelines (KFPv1 and KFPv2) if we set timeouts to components only. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Mohammad-nassar10** [comment]
If we set timeouts to components only it will not check timeout of the whole pipeline. We did an experiment (both in KFP v1 and v2). with two components that run for about 1 hour. Each component has timeout 2 hours without setting timeout for the pipeline. The two components completed in the experiments in KFP v1 and v2 as you can see in the attached screenshots.

V1:
![image](https://github.com/IBM/data-prep-kit/assets/79787844/e56f1a6c-01b0-45bf-ae31-2c6ceb11c4d8)
V2:
![image](https://github.com/IBM/data-prep-kit/assets/79787844/180624ec-a696-4ed2-bf3c-dba8ba992398)

We used the following pipeline:
```
import os
import kfp.compiler as compiler
import kfp.components as comp
import kfp.dsl as dsl
from kfp_support.workflow_support.utils import (
    ONE_HOUR_SEC,
    ComponentUtils,
)

def sleep1(timeInSec: int):
    import time
    time.sleep(timeInSec)

# prepare metrics parameters
sleep1_op = comp.func_to_container_op(
    func=sleep1, base_image="quay.io/dataprep1/data-prep-kit/kfp-data-processing:0.2.0"
)

@dsl.pipeline(
    name="timeout-test-pipeline",
    description="test timeout",
)
def tout(
    timeInSec: int = "3600",
    ):
    op1 = sleep1_op(timeInSec)
    ComponentUtils.add_settings_to_component(op1, ONE_HOUR_SEC * 2)

    op2 = sleep1_op(timeInSec)
    ComponentUtils.add_settings_to_component(op2, ONE_HOUR_SEC * 2)
    op2.after(op1)

if __name__ == "__main__":
    # Compiling the pipeline
    compiler.Compiler().compile(tout, __file__.replace(".py", ".yaml"))
```

**Comment by roytman** [comment]
@Mohammad-nassar10 , just to be sure, can you execute the same pipeline, when the component's e.g. 5 or 6 hours? Execute the pipeline over night or weekend.

**Comment by Mohammad-nassar10** [comment]
Will launch a run with more hours

**Comment by revit13** [comment]
on KFPv2 the pipeline run is finished after 12 hours where each component runs for 6 hours:


```bash
from workflow_support.compile_utils import ONE_HOUR_SEC, ONE_WEEK_SEC, ComponentUtils

import kfp.compiler as compiler
import kfp.components as comp
import kfp.dsl as dsl

# components
base_kfp_image = "quay.io/dataprep1/data-prep-kit/kfp-data-processing:0.2.0"

@dsl.component(base_image=base_kfp_image)
def sleep1(timeInSec: int):
    import time

    time.sleep(timeInSec)

@dsl.pipeline(
    name="timeout-test-pipeline",
    description="test timeout",
)
def toutnew(
    timeInSec: int = ONE_HOUR_SEC * 6,
    ):
    op1 = sleep1(timeInSec=timeInSec)
    ComponentUtils.add_settings_to_component(op1, ONE_HOUR_SEC * 10)

    op2 = sleep1(timeInSec=timeInSec)
    ComponentUtils.add_settings_to_component(op2, ONE_HOUR_SEC * 10)
    op2.after(op1)

if __name__ == "__main__":
    # Compiling the pipeline
    compiler.Compiler().compile(toutnew, __file__.replace(".py", ".yaml"))
```

**Comment by roytman** [comment]
Therefore we can remove pipeline timeouts from pipelines https://github.com/IBM/data-prep-kit/pull/270, and close this issue.
