### ISSUE TITLE
Add some minimal information about setting up VSCode

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#260]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

We have a small section about IDE Setup in the transforms directory README file that shows how to do the configuration for PyCharm, in order to setup the runtime virtual environment (that works for everything including ray modules?) We need a similar section about VSCode, since Dean reported that he couldn't resolve imports in the ray files that were implemented elsewhere in the repo. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
Think we did this one. @shahrokhDaijavad

**Comment by shahrokhDaijavad** [comment]
Thanks, @daw3rd. Yes, we did.
