### ISSUE TITLE
[Logging Feature Request] Displaying the fraction or percentage of total files processed by a given transform in the logs

### ISSUE THREAD

**Issue by dhirajjoshi16** [data-prep-kit/data-prep-kit#263]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### Feature

The current logs (for all transforms) show how many files have been processed at a given point of time. (e.g. see below). Displaying the fraction or percentage of total files processed (e.g., 150/2000 files processed in 10 min) will provide a better estimation of job completion time from an operations standpoint.

```
....INFO - Completed 373 files in 3.7426 min....
....INFO - Completed 423 files in 5.2355 min....
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
Fixed

**Comment by dhirajjoshi16** [comment]
Thanks a lot @blublinsky
