### ISSUE TITLE
Take the references to artifactory out of README files

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#276]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

A grep for the word artifactory , starting from root, found the following: 

./kfp/kfp_ray_components/README.md:export ARTIFACTORY_USER=<artifactory-user>
./kfp/kfp_ray_components/README.md:export ARTIFACTORY_API_KEY=<artifactory-key>
./data-processing-lib/python/README.md:To test, build and publish the library to artifactory
./data-processing-lib/ray/README.md:To test, build and publish the library to artifactory
./data-processing-lib/spark/README.md:To test, build and publish the library to artifactory

I will fix the last 3. @roytman Can you please fix the first 2? 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
@roytman I fixed the last 3 README files above and submitted a PR. Wasn't sure exactly what to do with the first 2 (above). Please take care of them. Thanks.

**Comment by roytman** [comment]
> @roytman I fixed the last 3 README files above and submitted a PR. Wasn't sure exactly what to do with the first 2 (above). Please take care of them. Thanks.

Done
