### ISSUE TITLE
[Bug] Example notebook output shows many ERROR messages.  

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#289]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

Looking at the [notebook example](https://github.com/IBM/data-prep-kit/blob/dev/examples/demo_with_launcher.ipynb), there are many ERROR messages, see below.  I think this has been fixed and a rerrun of the notebook will fix this.

15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte
15:47:28 ERROR - Error -> 'utf-8' codec can't decode byte 0x88 in position 119: invalid start byte

### Reproduction script

Follow the link above and see too many ERRORS.

### OS

Other

### Python

Other

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
I can test this, after @shivdeep-singh-ibm looks at it.

**Comment by revit13** [comment]
@shivdeep-singh-ibm It seems that [prepare_venv.sh](https://github.com/IBM/data-prep-kit/blob/dev/examples/prepare_env.sh) should be updated as it installs dependencies from requirements.txt files in transforms ray dirs that do not exist anymore.

**Comment by Bytes-Explorer** [comment]
This is coming from the old ingest2parquet module. When we move to code2parquet, this error should be fixed.

**Comment by shahrokhDaijavad** [comment]
@shivdeep-singh-ibm Looks like you have changed to code2parquet, but I now get errors in running that module in the notebook that seem to come from the wrong relative path. It is looking for a transforms subdirectory under the notebooks subdirectory for lang_extensions.json file. See below:


14:50:08 INFO - Running locally
14:50:08 INFO - data factory code2parquet_ is using local configuration without input/output path
14:50:08 INFO - data factory code2parquet_ max_files -1, n_sample -1
14:50:08 INFO - data factory code2parquet_ Not using data sets, checkpointing False, max files -1, random samples -1, files to use ['.parquet'], files to checkpoint ['.parquet']
14:50:08 INFO - data factory data_ is using local data access: input_folder - /Users/shahrokhdaijavad/Downloads/set5 output_folder - test-data/parquet_input
14:50:08 INFO - data factory data_ max_files -1, n_sample -1
14:50:08 INFO - data factory data_ Not using data sets, checkpointing False, max files -1, random samples -1, files to use ['.zip'], files to checkpoint ['.parquet']
14:50:08 INFO - pipeline id pipeline_id
14:50:08 INFO - code location {'github': 'github', 'commit_hash': '12345', 'path': 'path'}
14:50:08 INFO - number of workers 3 worker options {'num_cpus': 0.8, 'memory': 2147483648, 'max_restarts': -1}
14:50:08 INFO - actor creation delay 0
14:50:08 INFO - job details {'job category': 'preprocessing', 'job name': 'code2parquet', 'job type': 'ray', 'job id': 'job_id'}
2024-07-23 14:50:14,281	INFO worker.py:1744 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265/ 
(orchestrate pid=23025) 14:50:15 INFO - orchestrator started at 2024-07-23 14:50:15
(orchestrate pid=23025) 14:50:15 INFO - Number of files is 32, source profile {'max_file_size': 1.8488883972167969, 'min_file_size': 0.0022182464599609375, 'total_file_size': 12.004825592041016}
(orchestrate pid=23025) 14:50:15 INFO - Cluster resources: {'cpus': 10, 'gpus': 0, 'memory': 6.655619812197983, 'object_store': 2.0}
(orchestrate pid=23025) 14:50:15 INFO - Number of workers - 3 with {'num_cpus': 0.8, 'memory': 2147483648, 'max_restarts': -1} each
(orchestrate pid=23025) 14:50:15 ERROR - Error reading file /Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/examples/notebooks/transforms/code/code2parquet/python/test-data/languages/lang_extensions.json: [Errno 2] No such file or directory: '/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/examples/notebooks/transforms/code/code2parquet/python/test-data/languages/lang_extensions.json'
(orchestrate pid=23025) Traceback (most recent call last):
(orchestrate pid=23025)   File "/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/data-processing-lib/ray/src/data_processing_ray/runtime/ray/transform_orchestrator.py", line 83, in orchestrate
(orchestrate pid=23025)     "transform_params": runtime.get_transform_config(
(orchestrate pid=23025)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(orchestrate pid=23025)   File "/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/transforms/code/code2parquet/ray/src/code2parquet_transform_ray.py", line 103, in get_transform_config
(orchestrate pid=23025)     lang_dict = get_supported_languages(
(orchestrate pid=23025)                 ^^^^^^^^^^^^^^^^^^^^^^^^
(orchestrate pid=23025)   File "/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/transforms/code/code2parquet/python/src/code2parquet_transform.py", line 55, in get_supported_languages
(orchestrate pid=23025)     json_data, _ = data_access.get_file(lang_file)
(orchestrate pid=23025)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(orchestrate pid=23025)   File "/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/data-processing-lib/python/src/data_processing/data_access/data_access_local.py", line 367, in get_file
(orchestrate pid=23025)     raise e
(orchestrate pid=23025)   File "/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/data-processing-lib/python/src/data_processing/data_access/data_access_local.py", line 361, in get_file
(orchestrate pid=23025)     with open(path, "rb") as f:
(orchestrate pid=23025)          ^^^^^^^^^^^^^^^^
(orchestrate pid=23025) FileNotFoundError: [Errno 2] No such file or directory: '/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/examples/notebooks/transforms/code/code2parquet/python/test-data/languages/lang_extensions.json'
(orchestrate pid=23025) 14:50:15 ERROR - Exception during execution [Errno 2] No such file or directory: '/Users/shahrokhdaijavad/Documents/GitHub/data-prep-kit-testing-pdf/data-prep-kit/examples/notebooks/transforms/code/code2parquet/python/test-data/languages/lang_extensions.json': None
(raylet) [2024-07-23 14:50:23,180 E 23019 56837707] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-07-23_14-50-08_430620_22762 is over 95% full, available space: 15175614464; capacity: 494384795648. Object creation will fail if spilling is required.
14:50:25 INFO - Completed execution in 0.29202070236206057 min, execution result 1

**Comment by shivdeep-singh-ibm** [comment]
Please check this: https://github.com/IBM/data-prep-kit/pull/446

**Comment by shahrokhDaijavad** [comment]
Thanks, @shivdeep-singh-ibm This has been fixed.
