### ISSUE TITLE
[Feature] Define Release process

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#294]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

The project needs a release process, first, it can be done manually, but after that, it should be based on GitHub actions.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
This is almost complete.  We have merged in release-notes.md, RELEASE.md and scripts/release.sh.  Still a bit of work going on in a new PR #337 to get kfp publishing both v1 and v2 and to refine docs and scripts.
