### ISSUE TITLE
Ingest to parquet transform bug

### ISSUE THREAD

**Issue by sapthasurendran** [data-prep-kit/data-prep-kit#296]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

Got error while testing the new ingest_to_parquet module 
```
Traceback (most recent call last):
  File "/Users/sapthasurendran/Documents/GUF/data-prep-lab/data-prep-lab/data-processing-lib/python/src/data_processing/runtime/pure_python/transform_orchestrator.py", line 106, in orchestrate
    statistics.add_stats({"data access retries", retries})
  File "/Users/sapthasurendran/Documents/GUF/data-prep-lab/data-prep-lab/data-processing-lib/python/src/data_processing/transform/transform_statistics.py", line 34, in add_stats
    for key, val in stats.items():
                    ^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'items'
17:32:00 ERROR - Exception during execution 'set' object has no attribute 'items': None
```

### Reproduction script

dataset used: s3://dev-code-datasets/data-prep-labs/sample-datasets/set1/

### OS

MacOS (limited support)

### Python

3.10.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
Its fixed
Commit was merged just resently

**Comment by shahrokhDaijavad** [comment]
@blublinsky Which PR has the fix for this? @shivdeep-singh-ibm is also looking into this, as he is trying to use the new version in his Jupyter Notebook example.

**Comment by blublinsky** [comment]
profiler implementation

**Comment by shahrokhDaijavad** [comment]
@sapthasurendran Can you please try this, so we can close the issue? Thanks.

**Comment by sapthasurendran** [comment]
Tested. Works fine.

**Comment by shahrokhDaijavad** [comment]
Thanks, @sapthasurendran.
