### ISSUE TITLE
[Feature] Test All KFPv2 pipelines on an OpenShift AI server

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#312]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Test KFPv2 pipelines on an OpenShift AI server:

- [x] code quality
- [x] code to parquet
- [x] malware
- [x] prolong select
- [x] language ID
- [x] document ID
- [x]  exact dedup
- [x] fuzzy dedup
- [x] filter
- [x] tokenizations
- [x] profiler
- [x] noop
- [x] noop multiple

CC: @yuanchi2807 @shivdeep-singh-ibm @Bytes-Explorer 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by roytman** [comment]
@revit13 , you can use our OpenShift AI server, the working data science project is `kfpv2-tests`. 
Please store the test data in S3 storage and create the relevant secret.

**Comment by revit13** [comment]
btw lang id run fails due to an error reported in https://github.com/IBM/data-prep-kit/issues/285

**Comment by roytman** [comment]
Closing, as finished.
