### ISSUE TITLE
[Feature] Enable processing of local data by mounting local directories into the transform images

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#317]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

It will be useful if someone can take an image and run the image to apply the transform to data in the users' local file system, creating the transformed data in the local file system as well.  This can be done by mounting the input and output directories into the image and passing --data_local_config options to reference the mount points within the image.  However, do do this, we need to have locations in the image on which to mount the input and output directories.  To that end, all transforms images need a common pair of mount points.  This can be done in their Dockerfiles.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
We should also have some documentation and/or samples showing how to do this.

**Comment by blublinsky** [comment]
It will work without any changes.

**Comment by daw3rd** [comment]
This is addressed with pr #394
