### ISSUE TITLE
Fix the github doc pages formatting

### ISSUE THREAD

**Issue by nirmdesai** [data-prep-kit/data-prep-kit#32]
Several pages do not seem to render properly at the moment, e.g., https://ibm.github.io/data-prep-lab/transforms

Also, section heading with a trailing ":" look weird when you see the table of contents. Should remove the trailing ":" from section headings.

Attached screenshot shows what I see in Safari and Chrome.
<img width="294" alt="transforms_page_bottom" src="https://github.com/IBM/data-prep-lab/assets/11177239/5f9415e1-e558-4e67-8daf-ac2114723ef2">
<img width="1605" alt="transforms_page" src="https://github.com/IBM/data-prep-lab/assets/11177239/d08d172e-03f1-4992-99db-b8c9c2588674">
, also validated with one other person that this happens.

**Comment by shivdeep-singh-ibm** [comment]
Fixed in [this commit](https://github.com/IBM/data-prep-lab/commit/98c197632b804d0732f60ffde7caad23721250cb).

**Comment by nirmdesai** [comment]
Verified the fix.
