### ISSUE TITLE
Add an issues template for the repo

### ISSUE THREAD

**Issue by nirmdesai** [data-prep-kit/data-prep-kit#33]
We should define a template for submitting issues, to facilitate effective prioritization and clarity.

**Comment by daw3rd** [comment]
Fixed in PR #56

**Comment by Bytes-Explorer** [comment]
@daw3rd While creating a new feature request, the template asks me to select a component from the list is of existing transforms. However, if the feature request is for a new transform, what should be selected?

**Comment by daw3rd** [comment]
@Bytes-Explorer How about Transforms/Other
