### ISSUE TITLE
NLP Profiler location in the repo 

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#343]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### What happened + What you expected to happen

What happened?
NLP profiler is under universal transforms. 

What should happen?
NLP profiler should be under Tools as we are not transforming the data here. 

cc @daw3rd 

### Reproduction script

NA

### Anything else

NA

### OS

Ubuntu

### Python

3.10.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
The doc_quality transform is now under language.
