### ISSUE TITLE
[Feature] Replace compilation of the KFP workflow definitions  from "setup" to "build"

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#345]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Currently, KFP workflow definition compiled as a result of the `setup` Make target, it should be replaced by `build`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by revit13** [comment]
closed with https://github.com/IBM/data-prep-kit/pull/348
