### ISSUE TITLE
[Bug] The x-python:0.2.0 images are for arm64 platform

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#365]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

CI/CD

### What happened + What you expected to happen

The newly deployed  x-python:0.2.0  (e.g. noop-python:0.2.0) images are for arm64 platform and cannot be executed on Intel (amd64) machines. 
Should we deploy images for both architectures?

### Reproduction script

docker image inspect quay.io/dataprep1/data-prep-kit/noop-python:0.2.0 | grep Architecture
 "Architecture": "arm64",

### OS

MacOS (limited support)

### Python

3.10.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
This now fixed with the new DOCKER_PLATFORM macro in .make.defaults, which is now set to linux/amd64.

**Comment by daw3rd** [comment]
@roytman fixed?
