### ISSUE TITLE
Document is missing for building sequence of transforms

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#39]
When we click at the below link at the top level readme page,
<img width="745" alt="Screenshot 2024-05-01 at 5 47 26 PM" src="https://github.com/IBM/data-prep-lab/assets/55846138/c7c25ac4-8083-47a3-9984-faeff012fe3f">

It takes to the correct link, but looks like the document is missing there
<img width="814" alt="Screenshot 2024-05-01 at 5 49 22 PM" src="https://github.com/IBM/data-prep-lab/assets/55846138/c8d2b8b5-7be7-4953-9da1-c2d28978a2ff">

Please fix the link or add the missing document.

**Comment by daw3rd** [comment]
What page did you find this on?

**Comment by Bytes-Explorer** [comment]
On the top readme page. Added it [here](https://github.com/IBM/data-prep-lab/issues/39#issue-2273419381) as well.

**Comment by blublinsky** [comment]
@daw3rd, @Bytes-Explorer is this done? Can we remove it?

**Comment by Bytes-Explorer** [comment]
Yes, thank you
