### ISSUE TITLE
Running fdedup in the Notebook examples directory has a bug

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#399]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

This is the output from the cell that executes the Fuzzy Dedup module:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[10], line 5
      2 import sys
      4 from data_processing.utils import ParamsUtils
----> 5 from fdedup_transform_ray import FdedupRayTransformConfiguration
      7 # create parameters
      9 local_conf = {
     10     "input_folder": input_folder,
     11     "output_folder": output_folder,
     12 }

File ~/Documents/GitHub/data-prep-kit-testing/data-prep-kit/transforms/universal/fdedup/ray/src/fdedup_transform_ray.py:39
     30 from data_processing_ray.runtime.ray import (
     31     DefaultRayTransformRuntime,
     32     RayTransformFileProcessor,
     33     RayTransformLauncher,
     34     RayUtils,
     35 )
     36 from data_processing_ray.runtime.ray.runtime_configuration import (
     37     RayTransformRuntimeConfiguration,
     38 )
---> 39 from fdedup_support import (
     40     REQUEST_LEN,
     41     BucketsHash,
     42     BucketsHashProcessor,
     43     BucketsHashProcessorInvoker,
     44     DocCollector,
     45     DocsMinHash,
     46     MurmurMH,
     47     fuzzy_optimal_param,
     48     get_snapshot_folder,
     49 )
     50 from ray.actor import ActorHandle
     51 from ray.util import ActorPool

File ~/Documents/GitHub/data-prep-kit-testing/data-prep-kit/transforms/universal/fdedup/ray/src/fdedup_support.py:24
     22 from ray.actor import ActorHandle
     23 from ray.util import ActorPool
---> 24 from scipy.integrate import quad as integrate
     27 NO_SIMILARITY = -1
     28 REQUEST_LEN = 4096

ModuleNotFoundError: No module named 'scipy'

### Reproduction script

Run the Notebook in the examples directory, until you get to the fuzzy dedup module 

### OS

MacOS (limited support)

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shivdeep-singh-ibm** [comment]
Please check this https://github.com/IBM/data-prep-kit/pull/401

**Comment by shahrokhDaijavad** [comment]
Thanks, @shivdeep-singh-ibm . It's fixed.
