### ISSUE TITLE
Improve ray store used in repo level ordering module. 

### ISSUE THREAD

**Issue by shivdeep-singh-ibm** [data-prep-kit/data-prep-kit#421]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

In context of feature development in issue https://github.com/IBM/data-prep-kit/issues/283

### Reproduction script

The ray store used in the transform writes key,value pairs one by one to to Ray Actor.
This results in many network calls, It can be improved by adding something like `put_dict()` and `get_dict` which 
can improve performance.

### OS

Other

### Python

3.11.x

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
@shivdeep-singh-ibm can this be closed?

**Comment by shivdeep-singh-ibm** [comment]
Feature has been added and merged.
