### ISSUE TITLE
Add repo_name column to code2parquet tranform

### ISSUE THREAD

**Issue by sapthasurendran** [data-prep-kit/data-prep-kit#433]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

Add repository name to the code schema inside code2parquet transform. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
Is this completed @sapthasurendran ? If yes, pls close this issue.
