### ISSUE TITLE
[Feature] Enable transform() to terminate all processing of documents across all instances

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#437]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### Feature

Today we allow/expect exceptions to be thrown in a tranforms initi() and transform().  In the former case, this terminates all processing. In the latter case, this only serves to skip the current file being processed.  Per issue #430 resize needs to be able to stop processing of all files if a schema mismatch is encountered.  This can be done by having a special exception thrown from transform() that would cause the runtime to shutdown all future processing.  This likely involves signalling the (ray) orchestrator to shutdown.  Not sure how/if this can be handled in spark and python runtimes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
Done

**Comment by daw3rd** [comment]
This is fixed after 0.2.0 with new UnrecoverabledException.
