### ISSUE TITLE
[Feature] Create a demo notebook for RAG

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#451]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

The goal is to create a demo notebook for RAG that stitches the following components mentioned in the [issue](https://github.com/orgs/IBM/projects/86/views/1?filterQuery=&pane=issue&itemId=72179810). The notebook should reside in this folder https://github.com/IBM/data-prep-kit/tree/dev/examples/notebooks

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dolfim-ibm** [comment]
A first draft of the notebook is here https://github.com/IBM/data-prep-kit/pull/461. At the moment it still depends on some internal transforms which are being pushed soon.
