### ISSUE TITLE
[Feature] Chunking and Embedding transformations should preserve original text and page number

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#466]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

When we process PDFs we perform chunking and calculate embeddings.

Carry forward the following attribute through the process, and save them into final output

- `page_number` : where the chunk was calculated in original document (starting page is fine)
- `text` : actual raw text from doc

References:  #449 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by dolfim-ibm** [comment]
The original `text` should be in the `contents` column. The `page_number` will be added, thanks for the suggestion.

**Comment by dolfim-ibm** [comment]
This was included in https://github.com/IBM/data-prep-kit/pull/461
