### ISSUE TITLE
[Bug] handle spaces in file names

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#467]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

If I have a PDF named `My Important Document.pdf`  the transformation produces final parquet as `My%20Important%20Document.pdf`

We can either 
- preserve space in name (preferred)
- or replace spaces with `_` 

Also we need to keep the original filename in `filename` attribute

### Reproduction script

Feed a PDF with spaces in file name to the pipeline

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dolfim-ibm** [comment]
Interesting finding. I think the name change might originate from the `DataAccess` and the `transform_binary()`

@blublinsky @daw3rd what do you think?

**Comment by sujee** [comment]
closing.  Looks like the input files had wrong names to begin with
