### ISSUE TITLE
[Bug] html2parquet needs a Makefile to enable tests

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#513]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### What happened + What you expected to happen

Currently the transforms/universal/html2parquet directory is missing the standard Makefile.  As a result, tests are not being run for this transform - an oversight on the reviewer (me?).  In addition, `make test-src` seems to be failing in the python directory, but that will show up in the PR once you add the Makefile.

### Reproduction script

```
$ cd transforms/universal/html2parquet/
$ make -n test
make: *** No rule to make target `test'.  Stop.
```

### OS

MacOS (limited support)

### Python

3.11.x

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by sungeunan-ibm** [comment]
I will work on this issue.

**Comment by daw3rd** [comment]
There is now a Makefile and test-src and test-image pass (tested on rh)
