### ISSUE TITLE
[Bug] kfp worflow-test in ci/cd test.yml is not reproducible and may select an invalid dir.

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#514]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

CI/CD

### What happened + What you expected to happen

We found a failure of workflow-test in html2parquet, which was missing its Makefile.  Reviewing test.yml, it seems to be randomly selecting a transform (both v1 and v2) to run a test on.  This is not reproducible/predictable.  We should either
always run on noop or run on all (that have Makefiles).

### Reproduction script

dd

### Anything else

dd

### OS

Other

### Python

Other

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by roytman** [comment]
@daw3rd , I can understand reproducibility request, but have you observed the "invalid dir" case?

**Comment by roytman** [comment]
Testing all workflows will take a lot of time, on the other hand, testing only `noop` will not test all other workflows. 
Randomly choosing workflow guarantees that eventually all workflows will be tested.  
If you want to test a specific workflow, the "Workflow Manual Run" allows you to select a workflow and KFP version.
<img width="340" alt="image" src="https://github.com/user-attachments/assets/f55913b6-0dca-432a-b84c-27299510ade0">

**Comment by daw3rd** [comment]
The fix for this is to continue to select transform randomly, but to make sure the selection is from transforms that have a kfp_ray/Makefile.

**Comment by roytman** [comment]
Fixed in https://github.com/IBM/data-prep-kit/pull/530.
P.S. failures of https://github.com/IBM/data-prep-kit/pull/524 were not related to the issue
