### ISSUE TITLE
[Bug] PII Transform - has portion of the CI/CD testing disabled

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#517]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

When running the full suite of Ci/CD testing that includes PII Rredactor, the CI/CD failed due to memory issue. As the result, transform/pii_redactor/Makefile was renamed to transform/pii_redactor/Makefile.disable. A new PR need to be created to restore the Makefile and re-run full CICD

### Reproduction script

step 1: clone the repo and create new branch for testing
step 2: cd data-prep-kit/transforms/pii_redactor
Step 3: mv Makefile.disabled Makefile
Step 4: git add Makefile && git rm Makefile.disabled && git commit -s -m"Testing with recursive Makefile" 
Step 5: it push

### OS

MacOS (limited support)

### Python

3.10.x

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
The issue was narrowed down to test-image:: .transfroms.ray-test-image. 
This is still blowing up with OS Error and disabled in the current release. 
Issue will remain opened until this problem is solved.

**Comment by daw3rd** [comment]
@touma-I I believe this is fixed with the recent pr #538.  Can we close
