### ISSUE TITLE
Problem with MkDocs creation of GitHub pages 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#52]
MkDocs is having problems with certain MD file constructs, like "matrix" (MD table) on the root readme file. 

Compare https://github.com/IBM/data-prep-lab with https://ibm.github.io/data-prep-lab/ and see the problem.

Nirmit seems to have found a solution here: https://squidfunk.github.io/mkdocs-material/reference/data-tables/

Maybe, as the link says, by just adding the following lines to mkdocs.yml will fix the problem, no?

markdown_extensions:
  - tables

**Comment by shivdeep-singh-ibm** [comment]
Emojis need to be enabled in mkdocs config yaml. 
Fixed in https://github.com/IBM/data-prep-lab/pull/54

**Comment by blublinsky** [comment]
@shahrokhDaijavad If it is fixed, can we, please, remove this?
