### ISSUE TITLE
[Bug] Remove Test from published library release to pypi

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#531]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### What happened + What you expected to happen

The wheel currently deployed to Pypi includes test folder

### Reproduction script

pip install data-prep-toolkit=0.2.1.dev0

### OS

MacOS (limited support)

### Python

3.11.x

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
Solution is to modify pypropject.toml to exclude test folder from package_dir

[options]
package_dir = ["src"]

**Comment by touma-I** [comment]
Also modify .make.versions and publish distribution to pypi
```
make set-versions
make build-dist
make publish-dist

```

**Comment by daw3rd** [comment]
I have looked at the wheel (zip file) and there is no test or test-data.  The tar.gz does contain this, but that file contains everything from the project directory.

**Comment by daw3rd** [comment]
closing
