### ISSUE TITLE
[Bug] set-versions does not work for all files in the various git folders

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#541]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Makefiles

### What happened + What you expected to happen

When running `make set-versions`, the script worked for most files but missed the following:
transforms/language/doc_quality/ray/pyproject.toml
transforms/language/pii_redactor/python/pyproject.toml
transforms/language/pii_redactor/ray/pyproject.toml
transforms/universal/doc_id/python/pyproject.toml
transforms/universal/doc_id/ray/pyproject.toml
transforms/universal/ededup/ray/pyproject.toml
transforms/universal/html2parquet/python/pyproject.toml

### Reproduction script

update .make.versions to change the version tag, then run make .set-versions from the project root

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
Fixed with PR #548
