### ISSUE TITLE
[Bug] fasttext==0.9.2 doesn't  build/install with  GCC  v13 compiler

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#550]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### What happened + What you expected to happen

`pip install data-prep-toolkit-transforms-ray==0.2.1.dev1` fails on Ubuntu 24.04 with  GCC compiler version 13

This is due to `fasttext==0.9.2` dependency listed here : `transforms/language/lang_id/python/pyproject.toml`  line 13

## Work-around 1 - Install and use GCC version 11

```bash
## These instructions are for Ubuntu 22.04 and later

sudo apt update

## install GCC/G++ compilers version 11 
sudo apt install -y gcc-11  g++-11

## Verify installation
gcc-11  --version
g++-11  --version
# should say 11

## Set the compiler before doing pip install
CC=gcc-11  pip install  data-prep-toolkit-transforms-ray==0.2.1.dev1
```

## Fix 2 : upgrade to fasttext 0.9.3 (latest)

Update it here : `transforms/language/lang_id/python/pyproject.toml`  line 13

This compiles and installs cleanly.  Need to make sure the version upgrade doesn't introduce any other issues.

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
Thanks for raising this. I think this is getting addressed in this PR https://github.com/IBM/data-prep-kit/pull/545#discussion_r1734002685 cc @touma-I

**Comment by daw3rd** [comment]
@sujee can you confirm the fix?  Thanks.

**Comment by sujee** [comment]
confirming fix .  closing.
