### ISSUE TITLE
[Feature] HTML to Markdown (based on HTML2Parquet trafilatura code)

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#559]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

As a user, I'd like to be able to extract MD from HTML.
.The [HTML to Parquet](https://github.com/IBM/data-prep-kit/blob/dev/transforms/universal/html2parquet/python/README.md) transform today support only text extraction.  Since trafilatura also supports MD extraction, Is it possible to support adding a configuration parameter for the output format ( output_format=['text' | 'markdown') and then return markdown or text as the output? If so, the default output if no parameter is specified should be MD

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by Bytes-Explorer** [comment]
Can this be closed @touma-I

**Comment by shahrokhDaijavad** [comment]
Yes, it can be closed.
