### ISSUE TITLE
Add reference in notebooks to specific version of data-prep-toolkit

### ISSUE THREAD

**Issue by touma-I** [data-prep-kit/data-prep-kit#669]
In order to make sure that the notebook continues to work as expected without impact from future releases of the library, it is highly recommended to add data-prep-toolkit==0.2.1 to the requirements.txt file. Current and future releases of the transform have more relaxed requirements using add data-prep-toolkit>=x.x.x. However, as it relates to this particular notebook, it may not be desireable to pull in the latest release but, more appropriately, lock down a specific release. 

https://github.com/IBM/data-prep-kit/blob/359c1a46058ff88149d519a72b28dee256c0b537/examples/notebooks/rag/requirements.txt#L3

**Comment by shahrokhDaijavad** [comment]
@touma-I This is a good idea. For the rag example, both in the dev branch and in the notebook branch, this has already been done (By @sujee ), i.e., data-prep-toolkit==0.2.1 in the requirements.txt file. 

My mistake: 

You want 

data-prep-toolkit==0.2.1
data-prep-toolkit-ray==0.2.1

In addition to: 

data-prep-toolkit-transforms==0.2.1
data-prep-toolkit-transforms-ray==0.2.1

I

**Comment by touma-I** [comment]
Closing this issue as complete. cc: @shahrokhDaijavad
