### ISSUE TITLE
[Feature] Add a bibtex citation to the bottom of Readme

### ISSUE THREAD

**Issue by nirmdesai** [data-prep-kit/data-prep-kit#679]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

We should provide a Bibtex format citation for researchers who want to cite data-prep-kit if they use it for their research. The best place to put this would be at the bottom of the landing page.

Here is a good example from another project: https://github.com/IBM/unitxt

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
Added this to PR#680

**Comment by shahrokhDaijavad** [comment]
PR #680  has been merged now.
