### ISSUE TITLE
Various tests to verify that Python 3.12 works 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#683]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

Now that support for Python 3.12 has been merged ( #619 ), we need to test some examples to see if nothing is broken with 3.12. As a first test, let's try the rag example notebook. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
@shahrokhDaijavad can we close this issue ? Thanks

**Comment by shahrokhDaijavad** [comment]
Hi, @touma-I. I have not tested this myself, but based on Alexey and the Haifa team's successful tests, I think it is safe to close this.
