### ISSUE TITLE
Publish data-connector-lib to PyPI

### ISSUE THREAD

**Issue by hmtbr** [data-prep-kit/data-prep-kit#697]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

There is a request from a consumer of the data-connector-lib that he would like to install the lib from PyPI by pip: `pip install dpk_connector`. We need to publish the module there.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
As discussed, the release package name will be data-prep-connector and the initial release tag will be aligned with the current DPK release tag: data-prep-connector==0.2.2 (with the initial test release being 0.2.2.dev0 )

**Comment by hmtbr** [comment]
@touma-I Thanks for the review on my PR. Closing this as completed.
