### ISSUE TITLE
[Feature] Unify format of data_sets and files_to_use in DataAccessFactory

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#71]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### Feature

According to the way the data-processing-lib [parses the parameter data_data_sets](https://github.com/IBM/data-prep-lab/blob/d10895ecfe66e6dc513479e51c07429f1c0c0c11/data-processing-lib/src/data_processing/data_access/data_access_factory.py#L116C54-L116C63), the datasets should be passed as a line (String) with the names of the datasets separated by ",". For example dataset1,dataset2.
While the parameter data_files_to_use should be passed as a list (with []) that includes strings with '. For example ['.ext1', '.ext2'].

This difference is caused by the difference in parsing these two parameters in the library. I think we should unify the way of parsing by changing the way of parsing the data_data_sets to use type=ast.literal_eval. For example:
```python
parser.add_argument(
            f"--{self.cli_arg_prefix}data_sets",
            type=ast.literal_eval,
            default=None,
            help="List of data sets",
        )
```
### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
@daw3rd, this is done. Can we close it?

**Comment by daw3rd** [comment]
yes, we need to mark things "fixed", then they can get attention when browsing the issues.
