### ISSUE TITLE
[Feature] Need tests for DataAccessFactory data_sets, files_to_use and nsamples configurations.

### ISSUE THREAD

**Issue by daw3rd** [data-prep-kit/data-prep-kit#72]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Library/core

### Feature

DataAccessFactory uses parameters data_sets, files_to_use and nsamples to subset the input files selected for processing.  We have not tests to verify the proper implementation of these for

- [ ] DataAccessLocal
- [ ] DataAccessS3

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
data sets are tested here https://github.com/IBM/data-prep-lab/blob/dev/data-processing-lib/test/data_processing_tests/data_access/data_access_local_test.py#L33 and https://github.com/IBM/data-prep-lab/blob/dev/data-processing-lib/test/data_processing_tests/data_access/data_access_s3_test.py#L122, 
n_samples logic is tested here https://github.com/IBM/data-prep-lab/blob/dev/data-processing-lib/test/data_processing_tests/data_access/sample_input_data_test.py. Finally files to use are effectively exercised everywhere, as default is files to use = [.parquet]

**Comment by blublinsky** [comment]
@daw3rd can we close this one?

**Comment by daw3rd** [comment]
Yes this is fixed with this https://github.com/IBM/data-prep-kit/blob/dev/data-processing-lib/src/data_processing/test_support/data_access/data_access_factory_test.py
