### ISSUE TITLE
[Feature] Example notebook for DPK connector

### ISSUE THREAD

**Issue by Qiragg** [data-prep-kit/data-prep-kit#739]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

We do not have an example notebook demonstrating the use of DPK-connector for doing targeted crawls to support RAG. We would like to provide such an example.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
@Qiragg and @sujee to come up with a notebook and submit a PR

**Comment by touma-I** [comment]
Replace with https://github.com/IBM/data-prep-kit/issues/751
