### ISSUE TITLE
Build a new transform to automate crawling and then convert to parquet 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#751]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

This is using the DPK-connector lib in the repo (https://github.com/IBM/data-prep-kit/tree/dev/data-connector-lib) which is available as a stand-alone pip install now. This is about making this a "data ingestion" transform with parquet output that can easily be fed into other DPK transforms.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
@touma-I to get the code from the developers and adapt it to the DPK transform and submit a PR.

**Comment by Bytes-Explorer** [comment]
Request for consideration as we build this transform: 
1. Simple API call with minimal lines 
2. Explain what parameters are there in the API and how to use it in the readme
3. Request from Sujee on storing data 

![Image](https://github.com/user-attachments/assets/4b3e2f3a-4df5-4d8e-9350-32cb7fd5452d)

**Comment by touma-I** [comment]
@Bytes-Explorer Can you explain more why you need a structured/nested directory structure ? What are the motivation for it and how this will be used? There are two issues why we should NOT do it:
1) Web sites tend to have badly defined structure with cyclical graph 
2) The framework is not setup to handle nested folder. 
Please provide additional detail or we can skip this requirement for now.

**Comment by Bytes-Explorer** [comment]
@touma-I That requirement is from @sujee Lets discuss in the call. It is in the issue so that requests from our users are not missed on slack.

**Comment by touma-I** [comment]
@Bytes-Explorer here is what it looks like https://github.com/IBM/data-prep-kit/blob/dev/transforms/universal/web2parquet/web2parquet.ipynb  @sujee @shahrokhDaijavad This is now available with data--prep-toolkit-transforms[all]==0.2.2.dev3

**Comment by shahrokhDaijavad** [comment]
Thanks, @touma-I. Since I am making changes to the root README file on Monday, should I add this to the data ingestion part of the table (Python only) in that README, i.e., "advertise" about it, or is it premature?

**Comment by touma-I** [comment]
@shahrokhDaijavad Please do make the update. With this, we reach a key milestone for integrating acquisition and processing. I am sure as more and more people get to use it, it will evolve but based on latest testing, this is working as expected.

**Comment by Bytes-Explorer** [comment]
@touma-I I looked at the notebook! Fantastic work! You are setting a benchmark on how transforms should be written and how easy they should be to use. I will try it out later and will share if I have any suggestions. 

Agree with you, this should be advertised. 

cc @agoyal26
