### ISSUE TITLE
Update README file by adding links to the RAG and fine-tuning examples. 

### ISSUE THREAD

**Issue by shahrokhDaijavad** [data-prep-kit/data-prep-kit#752]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### Feature

Root REDAME page should be updated for the user to know where to go for RAG and fine-tuning examples. They are currently in the examples folder and may be hidden. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
@shahrokhDaijavad to own the actual deliverable on this one and submit a PR .
