### ISSUE TITLE
[Bug] error installing 'data-prep-toolkit-transforms[ray]==0.2.2.dev1'   using testpypi

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#759]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

Tried installing   'data-prep-toolkit-transforms[ray]==0.2.2.dev1'   using testpypi.
On both py311 and py312 envs.
Installation errors out.

[error on py311 env](https://gist.github.com/sujee/117ce182492634ed3a0a95ca980f3c9b)

[error on py312 env](https://gist.github.com/sujee/a92c7cbd65424ad138d58388bc8ec17b)

CC: @touma-I 

### Reproduction script

**Install steps on py311**

```bash
conda create -n dpk-022dev1-py311 -y python=3.11
conda activate dpk-022dev1-py311

# for linux
conda install gcc_linux-64
conda install gxx_linux-64

pip3 install --extra-index-url https://testpypi.python.org/pypi  'data-prep-toolkit-transforms[ray]==0.2.2.dev1'
```

**Install steps on py312**

```bash
conda create -n dpk-022dev1-py312 -y python=3.12
conda activate dpk-022dev1-py312

# for linux
conda install gcc_linux-64
conda install gxx_linux-64

pip3 install --extra-index-url https://testpypi.python.org/pypi  'data-prep-toolkit-transforms[ray]==0.2.2.dev1'
```

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shahrokhDaijavad** [comment]
Thanks for trying this, @sujee. But please wait for the release of 0.2.2.dev2 on pypi, by @touma-I. The way to make sure what we have on testpypi works is very "convoluted".

**Comment by sujee** [comment]
closing, moving to 0.2.2dev2
