### ISSUE TITLE
[Feature] Extend `doc_quality` to include stop words annotation

### ISSUE THREAD

**Issue by Harmedox** [data-prep-kit/data-prep-kit#811]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

There is a minimum number of stop words a document is expected to contain for it to be considered of good quality. This is used in preparing high-quality datasets like FineWeb.

**Proposal**:

- output column name -> docq_stop_words
- list of stop words should be parameterized
- default stop words -> ["the", "be", "to", "of", "and", "that", "have", "with"]

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dangxuanhong** [comment]
Hi @hamid-adebayo, I realized that counting english stop-words or common-words has already been [implemented](https://github.com/IBM/data-prep-kit/blob/821718a550135d5bac89e0b898f7e7d0be625111/transforms/language/doc_quality/python/src/doc_Gopher_statistics.py#L95) and annotated in column docq_contain_common_en_words [here](https://github.com/IBM/data-prep-kit/blob/821718a550135d5bac89e0b898f7e7d0be625111/transforms/language/doc_quality/python/src/doc_quality_transform.py#L148).

So, please consider using it by filtering out docs/rows having False value in that column. Recall that, this implementation is applied to en language only but the code is extendable to any other languages as long as their common stop words are provided.

**Comment by Harmedox** [comment]
Got it! Thanks @dangxuanhong
