### ISSUE TITLE
[Feature] Add spark support for filter module

### ISSUE THREAD

**Issue by Bytes-Explorer** [data-prep-kit/data-prep-kit#85]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/Other

### Feature

We want to support users who work with Spark, Ray and pure python. The goal is to enable the filter framework on Spark. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
This is done.
