### ISSUE TITLE
[Bug] dpk_web2parquet module is missing 0.2.2 release

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#863]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Other

### What happened + What you expected to happen

This import fails on release 0.2.2

`from dpk_web2parquet.transform import Web2Parquet`

Here is a check with recent releases
- :white_check_mark: 022 dev3   -- works
- :x: 022
- :white_check_mark: 023 dev1

### Reproduction script

install as follows

```bash
pip install data-prep-toolkit==0.2.2
pip install  data-prep-toolkit-transforms[html2parquet]==0.2.2
pip install data-prep-toolkit-transforms[web2parquet]==0.2.2
```

And  python code:

`from dpk_web2parquet.transform import Web2Parquet`

### OS

Ubuntu

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sujee** [comment]
related #838

**Comment by daw3rd** [comment]
@sujee I can not reproduce.  The following runs w/o error
```
rm -rf venv
python -m venv venv
source venv/bin/activate
pip install data-prep-toolkit==0.2.2
pip install  data-prep-toolkit-transforms[html2parquet]==0.2.2
pip install data-prep-toolkit-transforms[web2parquet]==0.2.2
python -c "from dpk_web2parquet.transform import Web2Parquet"
```

**Comment by daw3rd** [comment]
The following also works (note the removal of the `pip install data-prep-toolkit=0.2.2`)
```bash
rm -rf venv
python -m venv venv
source venv/bin/activate
pip install data-prep-toolkit-transforms[web2parquet]==0.2.2
python -c "from dpk_web2parquet.transform import Web2Parquet"
```

**Comment by sujee** [comment]
confirmed working now.  Closing
