### ISSUE TITLE
[Bug] Missing files on published docker images for latest tag - ray/kfp

### ISSUE THREAD

**Issue by juancappi** [data-prep-kit/data-prep-kit#904]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

CI/CD

### What happened + What you expected to happen

`doc_id` transform fails (at least also `ededup`) to run due to missing entry point script when using `latest` tag for `quay.io/dataprep1/data-prep-kit/doc_id-ray`:
```
...
10:04:21 INFO - job status is RUNNING
2024-12-31 10:04:18,697	INFO job_manager.py:528 -- Runtime env is setting up.
python: can't open file '/home/ray/doc_id_transform_ray.py': [Errno 2] No such file or directory
10:04:53 INFO - Job completed with execution status FAILED
...
```

### Reproduction script

Upon inspecting the container for: `quay.io/dataprep1/data-prep-kit/doc_id-ray:latest`, I can confirm the files are not there:

```
oc exec -n ray -it doc-id-kuberay-head-547xp -- /bin/bash
...
1000700000@doc-id-kuberay-head-qdg65:~$ pwd
/home/ray
1000700000@doc-id-kuberay-head-qdg65:~$ ls -l
total 80
drwxr-xr-x. 1 ray  users  4096 Sep 16 18:22 anaconda3
drwxr-xr-x. 2 ray  users  4096 Dec 17 12:02 data-processing-dist
drwxr-xr-x. 4 ray  users  4096 Dec 17 11:59 dpk_doc_id
-rw-r--r--. 1 ray  users  4284 Sep 17 16:41 pip-freeze.txt
-rw-r--r--. 1 ray  users     0 Dec 17 11:59 requirements.txt
-rw-r--r--. 1 2000 users 61406 Dec 31  2019 requirements_compiled.txt
```

I can also confirm the files exist for version `0.2.3`, which is the last before `latest`:
```
oc exec -n ray -it doc-id-kuberay-head-jc5x5 -- /bin/bash
1000700000@doc-id-kuberay-head-jc5x5:~$ ls -l
total 112
-rw-r--r--. 1 ray  users  1218 Dec 17 05:38 README.md
drwxr-xr-x. 1 ray  users  4096 Sep 16 18:22 anaconda3
drwxr-xr-x. 2 ray  users  4096 Dec 17 05:42 data-processing-dist
-rw-r--r--. 1 root root   4496 Dec 17 05:38 doc_id_transform_ray.py
drwxr-xr-x. 2 root root   4096 Dec 17 05:43 local
-rw-r--r--. 1 ray  users  4284 Sep 17 16:41 pip-freeze.txt
-rw-r--r--. 1 ray  users  1204 Dec 17 05:42 pyproject.toml
drwxr-xr-x. 1 ray  users  4096 Dec 17 05:42 python-transform
-rw-r--r--. 1 2000 users 61406 Dec 31  2019 requirements_compiled.txt
drwxr-xr-x. 1 ray  users  4096 Dec 17 05:43 src
drwxr-xr-x. 2 root root   4096 Dec 17 05:38 test
drwxr-xr-x. 4 root root   4096 Dec 17 05:38 test-data
```

### Anything else

@roytman could this be related to the image re-built which happened for the permission fix for `/home/ray` directory?
cc @touma-I 

### OS

Red Hat Enterprise Linux (RHEL)

### Python

3.10.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by touma-I** [comment]
@juancappi @roytman Could it be that we are in the middle of. transition between 0.2.3 and the alpha release for 1.0.0 on the outer repo? the alpha release builds both the doc_id and ededup as modules and the entry point is no longer doc_id_transform_ray.py  but it is now: -m dpk_doc_id.ray.transform  ?

**Comment by juancappi** [comment]
Mystery solved: the problem was that the `doc_id_wf.yaml` I was using was generated with the previous version of the code, pre-refactoring, and it was referencing `latest`, which at the time was `0.2.3` and it used the python script as the entry point. I re-generated the kfp pipeline yml using the latest and now the entry point got updated to `-m dpk_doc_id.ray.transform`, which solved the issue. 
Thank you @touma-I for the quick diagnosis
