### ISSUE TITLE
[Feature] Provide instructions to deploy and execute the project on a real Kubernetes cluster

### ISSUE THREAD

**Issue by roytman** [data-prep-kit/data-prep-kit#94]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

KFP workflows

### Feature

The currently provided Kind deployment is suitable for testing/development, but for processing of bigger size data sets, the users should execute the project on a real Kubernetes cluster. 
We have to provide instructions how to do it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
see https://github.com/IBM/data-prep-kit/pull/103

**Comment by roytman** [comment]
done by #116
